#! /usr/bin/env bash
# load files onto all connected Raspberry Pi Pico devices

if [ "$1" != "" ]
then
    # load a single Pico
    PORT=$1
else
    # load anything that looks like a Pico
    for p in `ls /dev/tty.usb*`
    do
        ./load_pico $p
    done
    exit 0  # all done
fi

echo "copying files to pico ${PORT}..."
rshell -p ${PORT} --buffer-size 512 <<HERE
cp main.py /pyboard
cp onoff.py /pyboard
cp config.py /pyboard
cp user_console.py /pyboard
cp user_pico.py /pyboard
cp energenie.py /pyboard
HERE
echo done: ${PORT}
